const express = require('express');
const path = require('path');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 8080;

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

const stats = { hooks: 0, scripts: 0, seo: 0 };

const scriptTemplates = {
    '15': (topic) => `[0-3s] HOOK:
"${topic} — here's what nobody tells you."

[3-10s] BODY:
Most people get this wrong. The truth is simpler than you think.

[10-15s] CTA:
Follow for more.`,
    '30': (topic) => `[0-3s] HOOK:
"Stop. If you care about ${topic}, this will change everything."

[3-10s] PROBLEM:
99% of people approach ${topic} the wrong way.

[10-20s] SOLUTION:
The truth? Consistency over intensity. Small daily actions compound.

[20-25s] EXAMPLE:
I went from struggling to thriving in 90 days — from boring basics done daily.

[25-30s] CTA:
Save this. Follow for more.`,
    '45': (topic) => `[0-3s] HOOK:
"Everything you know about ${topic} is probably wrong."

[3-10s] PROBLEM:
Most people fail because they follow advice from people who've never done it.

[10-20s] ROOT CAUSE:
It's not about knowledge. It's about execution.

[20-30s] SOLUTION:
I stopped consuming and started creating. 90 days. One thing. All in.

[30-40s] ACTION STEPS:
1. Pick your ONE thing
2. Set a 90-day deadline
3. Track daily
4. Share publicly
5. Fail forward

[40-45s] CTA:
Follow for more. Go make it happen.`,
    '60': (topic) => `[0-3s] HOOK:
"I was wrong about ${topic}. Here's what I learned."

[3-10s] STORY:
Two years ago, I knew everything about ${topic} but had nothing to show.

[10-20s] THE MISTAKE:
I was addicted to learning but allergic to doing.

[20-30s] WAKE-UP CALL:
Someone asked: "If you know so much, why haven't you done it?"

[30-40s] THE SHIFT:
I stopped learning for 90 days. I just DID. One action daily.

[40-50s] THE RESULT:
90 days later — more progress than 5 years combined.

[50-60s] LESSON + CTA:
You already know enough. Will you start? Follow for more.`
};

app.post('/api/script', (req, res) => {
    const { topic, duration, style } = req.body;
    const cleanTopic = topic || 'building wealth';
    const dur = duration || '30';
    const template = scriptTemplates[dur] || scriptTemplates['30'];
    const script = `AI Viral Toolkit - Script Output\nTopic: ${cleanTopic}\nDuration: ${dur}s\nStyle: ${style}\n\n${template(cleanTopic)}\n\n---\nGenerated by AI Viral Toolkit`;
    stats.scripts++;
    res.json({ script, success: true });
});

app.post('/api/hooks', (req, res) => {
    const { niche, tone } = req.body;
    const allHooks = {
        wealth: ["Stop trying to get rich. Do THIS instead.", "The reason you're broke? It's not what you think.", "Your salary is keeping you poor. Here's why.", "The rich don't save money. They do THIS.", "Passive income is a lie. Here's what works.", "This one habit cost me $100K.", "The money mistake 99% of people make.", "Why being frugal is making you poorer.", "I made $10K in 30 days. Here's the secret.", "The wealth principle schools don't teach."],
        mindset: ["Your mindset is the only thing between you and wealth.", "Alpha mindset: stop caring what others think.", "The 1% rule that changed my entire life.", "Why motivation is a trap.", "Discipline > Motivation. Here's why.", "The one thought pattern keeping you broke.", "Stop thinking. Start doing.", "Your comfort zone is a wealth killer.", "The mindset shift that made me a millionaire.", "Why 99% of people never change their life."],
        fitness: ["Stop doing cardio. Do THIS to lose fat.", "The one exercise nobody does but should.", "Why your workout is keeping you fat.", "I got abs in 30 days. Here's the secret.", "The fitness lie the industry hides.", "Stop counting calories. Do this instead.", "3 exercises that replaced my gym membership.", "Why most people fail at fitness.", "The 5-minute routine that changed my body.", "Your diet is wrong. Here's the truth."],
        ai: ["AI will replace your job. Do THIS now.", "This AI tool makes $10K/month.", "I automated my income with AI. Here's how.", "The AI tool nobody talks about.", "Stop paying for AI courses.", "AI made me $50K this year.", "The one AI skill that will make you rich.", "Why 90% of AI users use it wrong.", "This free AI tool beats ChatGPT.", "How to use AI to build wealth."],
        business: ["Stop starting businesses. Do THIS instead.", "I built a $100K business with $0.", "The business mistake that cost me $50K.", "Why 95% of businesses fail.", "The one business model that works in 2026.", "I fired all my clients. Here's why.", "The truth about entrepreneurship.", "Stop selling. Start doing THIS.", "How to start a business with zero money.", "The lazy business model that makes $500/day."],
        relationships: ["Stop chasing relationships. Do THIS instead.", "The relationship advice that works.", "Why you keep attracting the wrong people.", "The one skill that saved my marriage.", "Stop being nice. Start being respected.", "The truth about modern dating.", "Why your relationship patterns repeat.", "The boundary that changed my life.", "Stop fixing others. Fix this first.", "The mindset that attracts quality relationships."],
        productivity: ["Stop using to-do lists. Do THIS instead.", "The productivity system that changed my life.", "Why most productivity apps make you LESS productive.", "I tried 50 systems. This one won.", "The 2-minute rule that doubled my output.", "Stop managing time. Manage THIS.", "Why your morning routine wastes time.", "The one habit that replaced 10 others.", "Deep work > busy work.", "The productivity secret high performers know."],
        motivation: ["Motivation is a trap. Here's what works.", "Stop watching motivation videos.", "The truth about discipline.", "Why you're not lazy. You're doing this wrong.", "I stopped waiting for motivation.", "The one mindset shift that changed everything.", "Discipline is self-respect.", "Stop feeling inspired. Start being consistent.", "The motivation myth keeping you stuck.", "Why action beats motivation every time."]
    };
    const hooks = allHooks[niche] || allHooks.wealth;
    stats.hooks++;
    res.json({ hooks, success: true });
});

app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', stats });
});

app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, '0.0.0.0', () => {
    console.log(`AI Viral Toolkit running on port ${PORT}`);
});